# Generated by Django 2.0.1 on 2018-01-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('cute', '你覺得這個看聲可愛嘛？'), ('angel', '你覺得這個女生笑起來像天使嗎？')], default='cute', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=200)),
                ('source_url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voted_image_id', models.IntegerField()),
                ('voted_feature_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=50)),
                ('is_voted', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('features_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_id', to='api.Feature')),
                ('images_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_id', to='api.Picture')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='voterecord',
            unique_together={('images_id', 'features_id', 'user_id')},
        ),
    ]
