# Generated by Django 2.0.1 on 2018-01-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('like_count', models.IntegerField()),
                ('tags', models.CharField(choices=[('cute', 'cute'), ('angel', 'angel')], default='1', max_length=10)),
            ],
        ),
    ]
